# Generated by Django 3.2 on 2021-06-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_checkoutaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutaddress',
            name='apartment_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutaddress',
            name='street_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
