# Generated by Django 3.2 on 2021-06-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210628_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutaddress',
            name='zip_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
