# Generated by Django 3.2 on 2021-06-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210628_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutaddress',
            name='apartment_address',
        ),
        migrations.RemoveField(
            model_name='checkoutaddress',
            name='street_address',
        ),
        migrations.AddField(
            model_name='checkoutaddress',
            name='address',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='checkoutaddress',
            name='zip_code',
            field=models.CharField(default='', editable=False, max_length=15),
        ),
    ]
