# Generated by Django 3.2 on 2021-06-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_checkoutaddress_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutaddress',
            name='zip_code',
            field=models.CharField(blank=True, default=0, max_length=10),
        ),
    ]
