# Generated by Django 3.2 on 2021-06-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_checkoutaddress_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutaddress',
            name='zip_code',
            field=models.IntegerField(blank=True, max_length=5, null=True, verbose_name='zipcode'),
        ),
    ]
